/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_Authentification_ (void);
GtkWidget* create_Espace_Med_ (void);
GtkWidget* create_Gestion_De_Dons (void);
GtkWidget* create_Statistique2 (void);
GtkWidget* create_Statistique_1 (void);
GtkWidget* create_Affichage (void);
GtkWidget* create_Espaces_Admin_ETS (void);
GtkWidget* create_Gestions_De_ETS (void);
GtkWidget* create_Affichage_ETS (void);
GtkWidget* create_Statistiques (void);
GtkWidget* create_Espace_infirmier (void);
GtkWidget* create_Gestions_De_Donneurs (void);
GtkWidget* create_Donneur_Affichage (void);
GtkWidget* create_stat_rdv (void);
