/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *acceuil;
  GtkWidget *Authentification_;
  GtkWidget *Espace_Med_;
  GtkWidget *Gestion_De_Dons;
  GtkWidget *Statistique2;
  GtkWidget *Statistique_1;
  GtkWidget *Affichage;
  GtkWidget *Espaces_Admin_ETS;
  GtkWidget *Gestions_De_ETS;
  GtkWidget *Affichage_ETS;
  GtkWidget *Statistiques;
  GtkWidget *Gestions_De_Donneurs;
  GtkWidget *Espace_infirmier;
  GtkWidget *stat_rdv;
  GtkWidget *Donneur_Affichage;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  acceuil = create_acceuil ();
  gtk_widget_show (acceuil);
  /*Authentification_ = create_Authentification_ ();
  gtk_widget_show (Authentification_);
  Espace_Med_ = create_Espace_Med_ ();
  gtk_widget_show (Espace_Med_);
  Gestion_De_Dons = create_Gestion_De_Dons ();
  gtk_widget_show (Gestion_De_Dons);
  Statistique2 = create_Statistique2 ();
  gtk_widget_show (Statistique2);
  Statistique_1 = create_Statistique_1 ();
  gtk_widget_show (Statistique_1);
  Affichage = create_Affichage ();
  gtk_widget_show (Affichage);*/
  /*Espaces_Admin_ETS = create_Espaces_Admin_ETS ();
  gtk_widget_show (Espaces_Admin_ETS);
  Gestions_De_ETS = create_Gestions_De_ETS ();
  gtk_widget_show (Gestions_De_ETS);
  Affichage_ETS = create_Affichage_ETS ();
  gtk_widget_show (Affichage_ETS);
  Statistiques = create_Statistiques ();
  gtk_widget_show (Statistiques);*/
  /*Gestions_De_Donneurs = create_Gestions_De_Donneurs ();
  gtk_widget_show (Gestions_De_Donneurs);
  Espace_infirmier = create_Espace_infirmier ();
  gtk_widget_show (Espace_infirmier);
  stat_rdv = create_stat_rdv ();
  gtk_widget_show (stat_rdv);*/

  gtk_main ();
  return 0;
}

